services:
  - type: web
    name: orderi-server
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        value: https://mczxrgjuelqjmxbtzbxj.supabase.co
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: CORS_ORIGIN
        value: "*"
      - key: ORDERI_WEBHOOK_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
